###
POST {{content_host}}/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}

<> 2025-07-08T111611.200.json
<> 2025-07-08T111552.404.html
<> 2025-07-08T111531.404.html


### 课程分类查询
GET {{content_host}}/content/course-category/tree-nodes