###
POST {{content_host}}/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}

<> 2025-07-08T111611.200.json
<> 2025-07-08T111552.404.html
<> 2025-07-08T111531.404.html


### 课程分类查询
GET {{gateway_host}}/content/course-category/tree-nodes


### 查询某个课程的课程计划
GET {{gateway_host}}/content/teachplan/74/tree-nodes

### 新增课程计划--章
POST {{gateway_host}}/content/teachplan
Content-Type: application/json

{
  "courseId": 74,
  "parentid": 0,
  "grade": 1,
  "pname": "测试章节"
}


### 新增课程计划--节,从数据库找到第一级的课程计划id向其下边添加计划
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId": 74,
  "parentid": 247,
  "grade": 2,
  "pname": "小节名称 [点击修改]"
}

### 课程课程计划,需要从数据库找到修改的课程计划id
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "changeDate": null,
  "courseId": 22,
  "cousePubId": null,
  "createDate": null,
  "ctlBarShow": false,
  "ctlEditTitle": true,
  "endTime": null,
  "grade": "2",
  "isPreview": "1",
  "mediaType": "",
  "orderby": 1,
  "parentid": 237,
  "pname": "第1节修改名称",
  "startTime": null,
  "status": null,
  "teachPlanId": 240
}


### 删除课程计划
DELETE {{content_host}}/content/teachplan/43


### 查询课程教师
GET {{content_host}}/content/courseTeacher/list/72